site_name: Flare Proto

theme:
  name: material
  palette:
    scheme: slate
    primary: deep orange
  features:
    - navigation.indexes

plugins:
  - blog
  - tags


  
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra_css:
  - stylesheets/extra.css