site_name: Flare Proto
site_url: https://flare-proto.github.io/
site_description: random posts and shit from your local beeping proto

theme:
  name: material
  custom_dir: overrides

  palette:
    scheme: slate
    primary: deep orange
  features:
    - navigation.indexes
    - search.suggest
    - navigation.footer
  icon:
    tag:
      WX: material/weather-tornado

plugins:
  - meta
  - blog
  - tags
  - search



  
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/bluesky 
      link: https://bsky.app/profile/flare.protogen.club
    - icon: fontawesome/brands/github
      link: https://github.com/flare-proto
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@FlareProtogen
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@flareProto