site_name: Flare Proto

theme:
  name: material
  custom_dir: overrides

  palette:
    scheme: slate
    primary: deep orange
  features:
    - navigation.indexes
    - search.suggest
  icon:
    tag:
      WX: material/weather-tornado

plugins:
  - meta
  - blog
  - tags
  - search


  
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css