[project]
name = "flare-proto-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Flare", email = "git@flare.prtgn.org" }
]
requires-python = ">=3.14"
dependencies = [
    "cryptography>=50.0.1",
    "mkdocs-material[imaging]>=9.7.7",
    "pgpy13>=0.6.1rc1",
]

[project.scripts]
flare-proto-github-io = "flare_proto_github_io:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
