authors:
  flare:
    name: Flare
    description: Owner
    avatar: https://github.com/flare-proto.png
  annon:
    name: Annon
    description: Asked to remain anonymous
    avatar: https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Anonymous_emblem.svg/1024px-Anonymous_emblem.svg.png